name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r orchestrator/requirements.txt
        pip install -r agents/planner_agent/requirements.txt

    - name: Lint orchestrator
      run: |
        pip install flake8
        flake8 orchestrator/

    - name: Build Docker images
      run: |
        docker build -t orchestrator ./orchestrator
        docker build -t planner-agent ./agents/planner_agent

    - name: Push to Azure Container Registry (placeholder)
      run: echo "Push to ACR step goes here"

    - name: Deploy to AKS (placeholder)
      run: echo "Helm upgrade step goes here"
